# Generated by Django 5.0.4 on 2024-04-25 12:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=datetime.datetime(2024, 4, 25, 12, 27, 53, 757523, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default=datetime.datetime(2024, 4, 25, 12, 28, 37, 112538, tzinfo=datetime.timezone.utc), upload_to='profiles/photos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='portfolio.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
